# cargo-deny configuration (checked in CI).
# License allow-list matches the current dependency graph; extend deliberately.

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "ISC",
    "BSD-3-Clause",
    "Unicode-3.0",
    "CDLA-Permissive-2.0",
]

[bans]
multiple-versions = "warn"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
